---
title: "Learning Reflection"
subtitle: "Week 2"
format: html
editor: visual
---

# Learning reflections

Learning reflections are part of your weekly homework and have a weight of 20% of your final grade. Write a reflection in your own words on the different parts of the weeks material below. You can also use your learning reflections as a notebook as you work through exercises or readings. Write as much as you like, but a minimum of 100 words in total.

# Lecture

\<I watched the recording of the lecture and found it very engaging and supportive,
especially for beginners like me. I appreciated the instructor's effort to
create an inclusive environment where students could ask questions freely. The
live coding format was particularly helpful it allowed learners to follow along
and troubleshoot in real time. This interactive approach made coding feel less
intimidating and more manageable. Although I still find it challenging, I am
encouraged by the structure and delivery of the course. It is motivating to learn
alongside others, and I am genuinely looking forward to applying what I learn
in future assignments\>

# Homework Assignment

\<As someone new to coding, the Week 2 assignment was both challenging and
rewarding. I was introduced to essential R functions like mutate(), aes(), and labs()
and learned how data can be cleaned, transformed, and visualized to uncover
meaningful patterns. It was fascinating to see how a few lines of code could
produce clear, insightful plots. I can already see how these skills could
enhance how I communicate technical data to stakeholders in my current role.
Though many concepts are still new, completing the assignment has boosted my
confidence and sparked a deeper curiosity to keep learning coding.\>

# Readings

\<As someone new to coding, I found the Introduction to *R for Data Science* very helpful and encouraging. It explains the steps of working with data like importing, cleaning, transforming, and visualizing in a clear and simple way. I liked how it suggested starting with visualization, which feels more exciting and easier to understand. The reading makes data science feel more hands on and less intimidating. It gave me a better idea of what to expect and increased my interest in learning how to use R for real world data problems. I will definitely reread this and the other assigned readings.\>

# Submit learning reflections

## Stage, Commit & Push to GitHub

This final section introduces the workflow you need to follow at the end of each live coding exercise, homework assignment, learning reflection. It ensures that all the changes you have made to files in this repository (folder) are synced with the version that is stored on GitHub. The steps will be described at the end of each of the files.

1.  Open the Git pane in RStudio. It's in the top right corner in a separate tab.
2.  **Stage** your changes by checking appropriate box next to all files (if you select one file with your mouse, you can then highlight them all with Ctrl + A on your keyboard and check all boxes)
3.  Write a meaningful commit message (e.g. "Completed week 2 learning reflection") in the **Commit message** box
4.  Click **Commit**. Note that every commit needs to have a commit message associated with it.
5.  Click **Push** to send your changes to GitHub.
6.  Go to your wk-02-USERNAME GitHub repo (where USERNAME is your GitHub username) and refresh the page. You should see your commit message next to the updated files.

## Open an issue on GitHub

Once you have ensured that the Quarto document renders without errors and you have pushed all your changes to GitHub, it is to complete the assignment by opening an issue on your wk-02-USERNAME GitHub repo (where USERNAME is your GitHub username).

1.  Navigate to your wk-02-USERNAME GitHub repo (where USERNAME is your GitHub username).
2.  Click on **Issues**, and then **New issue** button.
3.  Write a meaningful title in the **Title** field
4.  Tag the course instructor with using the `@` sign in combination with `larnsce` as the username
5.  Add any questions or comments
